Pull Requests template
freecodecamp-wellington/freecodecamp-wellington.github.io pull request #23
Opened 2018-06-19 03:59 UTC by carlacfw

Pull requests template documentation for pull requests guidelines.
#6

2018-06-20 04:25 UTC, ojongerius requested changes
Awesome, thanks @carlacfw 🎉

2018-06-20 04:25 UTC, ojongerius commented on .github/CONTRIBUTING.md
> +Even if it is small improvement, adding a unit test will help to ensure no regressions or the issue is not re-introduced.
even if it is **a** small improvement?

2018-06-20 04:25 UTC, ojongerius commented on .github/PULL_REQUEST_TEMPLATE.md
> +  * Ex. "Fixes regression on encoding vnd headers" > "Fixed encoding bug", which forces the reader to look at code to understand impact.
on encoding **and** headers?

2018-06-20 04:25 UTC, ojongerius commented on .github/PULL_REQUEST_TEMPLATE.md
> +  * GitHub will automatically close change with this syntax.
will automatically close **changes**?

2018-06-20 04:25 UTC, ojongerius commented on .github/issue_template.md
> +* Firmware Version:
Firmware version is not relevant to us

2018-06-20 04:25 UTC, ojongerius commented on .github/issue_template.md
> +* SDK version:
SDK not relevant to us either

2018-06-20 04:25 UTC, ojongerius commented on .github/issue_template.md
> +* Toolchain version:
Toolchain is not applicable

2018-07-22 04:13 UTC, merged

2018-07-22 04:13 UTC, ojongerius commented
Just got back from holidays 😄 Thanks @carlacfw!

2018-07-22 05:20 UTC, carlacfw commented
Cool, hope you have had a great holiday! Welcome back then haha

On 22 July 2018 at 16:13, Otto Jongerius <notifications@github.com> wrote:

> Just got back from holidays 😄 Thanks @carlacfw
> <https://github.com/carlacfw>!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/freecodecamp-wellington/freecodecamp-wellington.github.io/pull/23#issuecomment-406839821>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/Aa0vU1oJg9B75hQS_8UHf6Gx95gxwh0nks5uI_vjgaJpZM4Usz52>
> .
>